/* this file is @generated by seesaw */

trait YakShaver {
    #[doc = " create a yakshaver"]
    unsafe fn create() -> *mut yakshaver;
    #[doc = " destroy a yakshaver"]
    unsafe fn destroy(arg1: *mut yakshaver);
    #[doc = " get number of yaks shaved"]
    unsafe fn yaks_shaved(arg1: *const yakshaver) -> ::std::os::raw::c_uint;
    #[doc = " shave some yaks"]
    unsafe fn shave(arg1: *mut yakshaver) -> ::std::os::raw::c_int;
}
